"""add mfa columns to users

Revision ID: 344eeaaeff06
Revises: bce90c9da466
Create Date: 2026-04-02 12:58:00.752772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344eeaaeff06'
down_revision: Union[str, Sequence[str], None] = 'bce90c9da466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'mfa_secret')
    # ### end Alembic commands ###
