"""add saml providers table

Revision ID: 93f4a8bd65e1
Revises: 352753a76285
Create Date: 2026-04-09 10:07:21.093840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f4a8bd65e1'
down_revision: Union[str, Sequence[str], None] = '352753a76285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saml_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('acs_url', sa.String(), nullable=False),
    sa.Column('metadata_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saml_providers_entity_id'), 'saml_providers', ['entity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saml_providers_entity_id'), table_name='saml_providers')
    op.drop_table('saml_providers')
    # ### end Alembic commands ###
